- user:
    name: aur_builder
    create_home: yes
  tags:
    - config

- lineinfile:
    path: /etc/sudoers.d/aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: {{ item }}'
    create: yes
    validate: 'visudo -cf %s'
  loop:
    - /usr/bin/pacman
  tags:
    - config

- name: Install dependencies
  package:
    name:
      - git
      - go
      - base-devel
    state: present
  tags:
    - install

- name: Install yay
  block:
    - name: Create directory for build
      tempfile:
        state: directory
      register: builddir
    - name: Download package from the AUR
      unarchive:
        remote_src: yes
        src: "https://aur.archlinux.org/cgit/aur.git/snapshot/yay.tar.gz"
        dest: "{{ builddir.path }}"
    - name: Run makepkg
      shell: cd '{{ builddir.path | quote }}/yay' && makepkg -rsi --noconfirm
  always:
    - name: Remove build directory
      file:
        state: absent
        path: "{{ builddir.path }}"
  become_user: aur_builder
  tags:
    - install

- name: Upgrade aur packages
  command: yay -Syu --noconfirm
  become: yes
  become_user: aur_builder
  tags:
    - upgrade
