- user:
    name: aur_builder
    create_home: yes
  tags:
    - config

- lineinfile:
    path: /etc/sudoers.d/aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: {{ item }}'
    create: yes
    validate: 'visudo -cf %s'
  loop:
    - /usr/bin/pacman
  tags:
    - config

- name: Install dependencies
  package:
    name:
      - git
      - go
      - base-devel
  tags:
    - install

- name: Install yay
  kewlfft.aur.aur:
    name: yay
  become: yes
  become_user: aur_builder
  tags:
    - install

- name: Upgrade aur packages
  kewlfft.aur.aur:
    upgrade: yes
  become: yes
  become_user: aur_builder
  tags:
    - upgrade
