- name: Repos by Include
  ini_file:
    path: /etc/pacman.conf
    section: "{{ item.name }}"
    option: Include
    value: "{{ item.include }}"
  when: item.include is defined
  loop: "{{ pacman_repos }}"
  tags:
    - config

- name: Repos by server
  ini_file:
    path: /etc/pacman.conf
    section: "{{ item.name }}"
    option: Server
    value: "{{ item.server }}"
  when: item.server is defined
  loop: "{{ pacman_repos }}"
  tags:
    - config

- name: 'Install'
  template:
    src: checkupdatesafety.j2
    dest: '/usr/local/bin/checkupdatesafety'
    mode: '0700'
    owner: root
    group: root
  tags:
    - config

- name: Update cache
  pacman:
    update_cache: yes
  tags:
    - upgrade
    - install
    
- name: Upgrade packages
  pacman:
    upgrade: yes
  tags:
    - upgrade
    
- name: Upgrade aur packages
  aur:
    upgrade: yes
  become: yes
  become_user: aur_builder
  tags:
    - upgrade

- name: Utilites
  package:
    name:
      - base-devel
      - pacman-contrib
  tags:
    - install

- name: Install console utilities
  package:
    name:
      - tmux
      - mosh
      - wget
      - htop
      - iotop
      - rsync
  tags:
    - install
