- name: 'Install'
  template:
    src: checkupdatesafety.j2
    dest: '/usr/local/bin/checkupdatesafety'
    mode: '0700'
    owner: root
    group: root
  tags:
    - config

- name: Configure pacman hook dir
  file:
    path: "/etc/pacman.d/hooks"
    mode: '0755'
    state: directory
  tags:
    - config

- include_role:
    name: util-package-upgrade
  tags:
    - upgrade

- name: Utilites
  package:
    name:
      - base-devel
      - pacman-contrib
    state: present
  tags:
    - install
