- name: 'Create pacman config'
  template:
    src: "pacman.conf.j2"
    dest: "/etc/pacman.conf"
    mode: '0644'
  tags:
    - config

- name: 'Create mirrorlist'
  template:
    src: "mirrorlist.j2"
    dest: "/etc/pacman.d/mirrorlist"
    mode: '0644'
  when: pacman_mirrorlist is defined
  tags:
    - config

- name: 'Install'
  template:
    src: checkupdatesafety.j2
    dest: '/usr/local/bin/checkupdatesafety'
    mode: '0700'
    owner: root
    group: root
  tags:
    - config

- name: Update cache
  pacman:
    update_cache: yes
  tags:
    - upgrade

- name: Update keyring first
  shell: pacman -S --noconfirm archlinux-keyring
  tags:
    - upgrade

- name: Upgrade packages
  pacman:
    upgrade: yes
  tags:
    - upgrade

- name: Utilites
  package:
    name:
      - base-devel
      - pacman-contrib
  tags:
    - install

- name: Install console utilities
  package:
    name:
      - tmux
      - mosh
      - wget
      - htop
      - iotop
      - rsync
  tags:
    - install
