- name: Install additional packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{software_packages}}"
  tags:
    - install

- name: Install additional packages Arch
  package:
    name: "{{ item }}"
    state: present
  loop: "{{software_packages_arch}}"
  when: ansible_os_family == "Archlinux"
  tags:
    - install

- name: Install additional packages Debian
  package:
    name: "{{ item }}"
    state: present
  loop: "{{software_packages_debian}}"
  when: ansible_os_family == "Debian"
  tags:
    - install

- name: Install flatpak
  package:
    name: flatpak
    state: present
  when: software_flatpaks is defined
  tags:
    - install

- name: Install custom flatpaks
  flatpak:
    name: "{{ item }}"
  loop: "{{software_flatpaks}}"
  when: software_flatpaks is defined
  tags:
    - install

- name: Update flatpaks
  command: "flatpak update --noninteractive"
  when: software_flatpaks is defined
  tags:
    - upgrade
