#!/bin/bash
. /usr/local/bin/storage_helpers

XMPP_DESTINATION=( )
SEND_XMPP_EXECUTABLE="sendxmpp"
OVERALL_RC=0

[ -f /etc/backupcfg ] && . /etc/backupcfg

[ "$DEBUG" = 1 ] && set -x

function xmpp {
	if [ -f "$1" ]
	then
		for current in "${XMPP_DESTINATION[@]}"
		do
			echo "$IDENTIFIER Sending file: $1" | "$SEND_XMPP_EXECUTABLE" -f /root/.sendxmpprc -t -n "$current" 2>> "$LOG_FILE"
			"$SEND_XMPP_EXECUTABLE" -m "$1" -f /root/.sendxmpprc -t -n "$current" 2 >> "$LOG_FILE"
		done
		echo "$1" >> "$LOG_FILE"
	else
		for current in "${XMPP_DESTINATION[@]}"
		do
			echo "$IDENTIFIER $@" | "$SEND_XMPP_EXECUTABLE" -f /root/.sendxmpprc -t -n "$current" 2>> "$LOG_FILE"
		done
		echo "$@" >> "$LOG_FILE"
	fi
}

function cleanup {
	rm -f "$LOCKFILE"
	exit "$OVERALL_RC"
}

function backup {
	INTERVAL="$2"

	if [ -n "$1" ]
	then
		STORAGE_META_DIR="$1"
	else
		xmpp Storage meta dir needs to be given as first parameter
		return 1
	fi

	if [ -z "$INTERVAL" ]
	then
		INTERVAL=hourly
	fi

	MOUNTPOINT="$(getMountpoint "$STORAGE_META_DIR")"
	RSYNC_PARAMS="-a --delete --ignore-errors"
	BACKUP_FOLDER="$MOUNTPOINT"/backup
	MARKER_FILE="$BACKUP_FOLDER"/.backup
	IDENTIFIER=$(echo ${HOSTNAME}_$(getPoolName $STORAGE_META_DIR) | tr / _ | tr -s '_')
	LOG_FILE="/var/log/backup_$IDENTIFIER"

	FAILED=0

	LOCKFILE="/var/lock/backup_$IDENTIFIER"

	[ -e "$LOCKFILE" ] && { xmpp Lockfile $LOCKFILE exists, stopping backup; return 1; }

	trap cleanup EXIT

	touch "$LOCKFILE"

	echo Start `date` > "$LOG_FILE"


	function sendLogFile {
		if [ -n "$LOG_FILE" ]
		then
			xmpp "Errors occured in subcommand, sending log file:"
			xmpp "$LOG_FILE"
		fi
	}

	function getLatestSnapshot {
		FOLDER="$1"

		if [ -d "$FOLDER" -a -d "$FOLDER/.snapshots" ]
		then
			SNAPSHOT=`echo "$FOLDER/.snapshots/$(ls "$FOLDER/.snapshots/" | sort -g -u | tail -n 1)/snapshot/"`
			if [ -d "$SNAPSHOT" ]
			then
				echo "$SNAPSHOT"
			fi
		else
			echo "";
		fi

	}

	#xmpp "Running as user $(whoami)@$HOSTNAME in dir $(pwd)"

	#xmpp "Starting backup"

	if [ ! -d "$BACKUP_FOLDER" ]
	then
		xmpp "$BACKUP_FOLDER is missing! Aborting..."
		return 1
	fi

	if [ -e "$BACKUP_FOLDER/.rsnapshot.conf" ]
	then
		xmpp "Perform backup with rsnapshot"

		CONTINUE=0
		NEEDED_SPACE=0
		for C in $(cat "$BACKUP_FOLDER/.rsnapshot.conf" | grep -i ^backup | tr -s '[:space:]' | cut -f 2)
		do
			[ "$( ls -A "$C" | wc -l )" -eq 0 ] && xmpp "No content in $C" && CONTINUE=1 && break;
			CURRENT_SOURCE=`getLatestSnapshot "$C"`
			if [ -z "$CURRENT_SOURCE" ]
			then
				xmpp "Snapshot for $CURRENT does not exist, using live data for size estimation"
				CURRENT_SOURCE="$C"
			fi
			NEEDED_SPACE=$(($NEEDED_SPACE + `du -m -d 0 "$CURRENT_SOURCE" | cut -f 1`))
		done

		FREE_SPACE=`df --output=avail -m "$BACKUP_FOLDER" | tail -n 1`

		FREE_SPACE=$(($FREE_SPACE + `du -d 0 -m "$BACKUP_FOLDER" | cut -f 1`))

		if [ "$NEEDED_SPACE" -gt "$FREE_SPACE" ]
		then
			xmpp Not enough space for backup
			CONTINUE=1
		fi


		if [ "$CONTINUE" -eq 0 ]
		then
			echo ---------------
			rsnapshot -t -c "$BACKUP_FOLDER/.rsnapshot.conf" "$INTERVAL" | sed -e "N;s|\\\\\n| |p;d;" | grep rsync
			echo ---------------
			ionice -c 2 -n 7 rsnapshot -v -c "$BACKUP_FOLDER/.rsnapshot.conf" "$INTERVAL" 2>&1 | tee -a "$LOG_FILE" 

			RESULT_RSNAPSHOT="${PIPESTATUS[0]}"
			RESULT_MESSAGE="Backup of $BACKUP_FOLDER"

			if [ "$RESULT_RSNAPSHOT" -eq 0  ]
			then
				RESULT_MESSAGE="$RESULT_MESSAGE successful"
				echo "$(getTimestamp)" > "$STORAGE_META_DIR"/backup_last_success
			else
				RESULT_MESSAGE="$RESULT_MESSAGE failed with status code $RESULT_RSYNC"
				echo "$(getTimestamp)" > "$STORAGE_META_DIR"/backup_last_fail
				sendLogFile
				return 1
			fi
		else
			RESULT_MESSAGE="$RESULT_MESSAGE failed, at least one source empty"
			echo "$(getTimestamp)" > "$STORAGE_META_DIR"/backup_last_fail
			sendLogFile
			return 1
		fi

		xmpp "$RESULT_MESSAGE"

	elif [ -e "$BACKUP_FOLDER/.backup" ]
	then
		xmpp "Perform backup with rsync"

		SNAPSHOT_FOLDERS=""
		FAILURES=0
		while read CURRENT_SOURCE
		do
			if [ -z "$CURRENT_SOURCE" ]
			then
				continue
			fi

			if [ ! -d "$CURRENT_SOURCE" ]
			then
				xmpp "Line $CURRENT_SOURCE from $MARKER_FILE does not contain a valid source folder"
				FAILURES=$(( FAILURES + 1 ))
				continue
			elif [ "$( ls -A "$CURRENT_SOURCE" | wc -l )" -eq 0 ]
			then
				xmpp "Line $CURRENT_SOURCE from $MARKER_FILE contains empty source folder"
				FAILURES=$(( FAILURES + 1 ))
				continue
			else
				SNAPSHOT_FOLDERS="$SNAPSHOT_FOLDERS$CURRENT_SOURCE/
	"
			fi
		done < "$MARKER_FILE"

		NEEDED_SPACE=0

		while read CURRENT
		do
			if [ -z "$CURRENT" ]
			then
				continue
			fi

			CURRENT_SOURCE=`getLatestSnapshot "$CURRENT"`

			if [ -z "$CURRENT_SOURCE" ]
			then
				xmpp "Snapshot for $CURRENT does not exist, using live data for size estimation"
				CURRENT_SOURCE="$CURRENT"
			fi

			NEEDED_SPACE=$(($NEEDED_SPACE + `du -m -d 0 "$CURRENT_SOURCE" | cut -f 1`))
		done <<< "$SNAPSHOT_FOLDERS"

		FREE_SPACE=`df --output=avail -m "$BACKUP_FOLDER" | tail -n 1`

		FREE_SPACE=$(($FREE_SPACE + `du -d 0 -m "$BACKUP_FOLDER" | cut -f 1`))

		if [ "$NEEDED_SPACE" -gt "$FREE_SPACE" ]
		then
			xmpp Not enough space for backup
			return 1
		fi

		while read CURRENT
		do
			if [ -z "$CURRENT" ]
			then
				continue
			fi

			CURRENT_DIR_NAME="`basename $CURRENT`"

			# find most current snapshot

			CURRENT_SOURCE=`getLatestSnapshot "$CURRENT"`
			if [ -z "$CURRENT_SOURCE" ]
			then
				xmpp "Snapshot for $CURRENT does not exist, using live data for backup"
				CURRENT_SOURCE="$CURRENT"
			fi

			if [ 0 -eq $(ls $CURRENT_SOURCE | wc -l) ]
			then
				xmpp "Source $CURRENT_SOURCE is empty, skipping"
				continue
			fi

			DESTINATION="$BACKUP_FOLDER/$CURRENT_DIR_NAME/"

			xmpp "Backing up $CURRENT_SOURCE to $DESTINATION"


			if [ ! -d "$DESTINATION" ]
			then
				mkdir "$BACKUP_FOLDER/$CURRENT_DIR_NAME"
			fi

			ionice -c 2 -n 7 rsync $RSYNC_PARAMS "$CURRENT_SOURCE" "$DESTINATION" >> "$LOG_FILE" 2>&1

			RESULT_RSYNC="$?"

			RESULT_MESSAGE="Backup of $CURRENT_DIR_NAME"

			if [ "$RESULT_RSYNC" -eq 0  ]
			then
				RESULT_MESSAGE="$RESULT_MESSAGE successful"
				echo "$(getTimestamp)" > "$STORAGE_META_DIR"/backup_last_success
			else
				RESULT_MESSAGE="$RESULT_MESSAGE failed with status code $RESULT_RSYNC"
				echo "$(getTimestamp)" > "$STORAGE_META_DIR"/backup_last_fail
			fi

			xmpp "$RESULT_MESSAGE"

		done <<< "$SNAPSHOT_FOLDERS"

		if [ "$FAILURES" -gt 0 ]
		then
			echo "$(getTimestamp)" > "$STORAGE_META_DIR"/backup_last_fail
			xmpp "$FAILURES source folders could not be used"

			sendLogFile
			return 1
		fi
	else
		xmpp "$BACKUP_FOLDER does not contain usable backup config file! Aborting..."
		return 1
	fi

	rm -f "$LOCKFILE"
}

MODE="$1"
shift
STORAGE_META_DIR="$1"

if [ -z "$MODE" ]
then
	echo "Usage:
storage_backup auto
  Run automatic backups as defined in /etc/storage/autobackup
storage_backup backup <metadir>
storage_backup check <metadir>
storage_backup create <metadir> rsync
storage_backup create <metadir> rsnapshot
storage_backup add <metadir> <sourcedir>"
fi

function createBackupRsync {
	! command -v rsync 2>&1 > /dev/null && echo rsync missing && exit 1
	STORAGE_META_DIR="$1"
	MOUNT_DIR="$(getMountpoint "$STORAGE_META_DIR")"
	mkdir -p "$MOUNT_DIR/backup"
	touch "$MOUNT_DIR/backup/.backup"
}

function createBackupRsnapshot {
	! command -v rsnapshot 2>&1 > /dev/null && echo rsnapshot missing && exit 1

	STORAGE_META_DIR="$1"
	MOUNT_DIR="$(getMountpoint "$STORAGE_META_DIR")"
	mkdir -p "$MOUNT_DIR/backup"
	touch "$MOUNT_DIR/backup/.backup"
	BACKUP_NAME="$(getPoolName "$STORAGE_META_DIR")"

	cat << EOF > "$MOUNT_DIR/backup/.rsnapshot.conf"
config_version	1.2
snapshot_root	$MOUNT_DIR/backup

no_create_root	1

cmd_rm		/usr/bin/rm
cmd_rsync	/usr/bin/rsync
cmd_logger	/usr/bin/logger

retain	hourly	5
retain	daily	5

verbose		2
loglevel	3

lockfile	/var/run/rsnapshot.$BACKUP_NAME.pid

EOF

	echo
}

function createBackup {
	echo createBackup "$@"
	STORAGE_META_DIR="$1"
	TYPE="$2"

	case $TYPE in
		rsync) createBackupRsync "$@" ;;
		rsnapshot) createBackupRsnapshot "$@" ;;
		*) echo "Unknown backup type"; return 1 ;;
	esac
}

function add {
	echo add "$@"
	STORAGE_META_DIR="$1"
	SOURCE_DIR="$2"
	[ -z "$SOURCE_DIR" ] && echo Source directory is missing && return 1

	[ -f "$(getMountpoint "$STORAGE_META_DIR")/backup/.backup" ] && TYPE=rsync
	[ -f "$(getMountpoint "$STORAGE_META_DIR")/backup/.rsnapshot.conf" ] && TYPE=rsnapshot

	case $TYPE in
		rsync) echo "$SOURCE_DIR" >> "$(getMountpoint "$STORAGE_META_DIR")/backup/.backup" ;;
		rsnapshot) echo "backup		$SOURCE_DIR	." >> "$(getMountpoint "$STORAGE_META_DIR")/backup/.rsnapshot.conf" ;;
		*) echo "Unknown backup type"; return 1 ;;
	esac
}

function check {
	STORAGE_META_DIR="$1"
	LAST_SUCCESS=
	LAST_FAIL=
	[ -f "$STORAGE_META_DIR"/backup_period ] && PERIOD=$(cat "$STORAGE_META_DIR"/backup_period)
	[ -z "$PERIOD" ] && PERIOD=24
	[ -f "$STORAGE_META_DIR"/backup_last_success ] && LAST_SUCCESS=$(cat "$STORAGE_META_DIR"/backup_last_success)
	[ -f "$STORAGE_META_DIR"/backup_last_fail ] && LAST_FAIL=$(cat "$STORAGE_META_DIR"/backup_last_fail)
	[ -n "$LAST_FAIL" ] && LAST_FAIL_MESSAGE=", last fail on $(parseTimestamp $LAST_FAIL)"
	[ -z "$LAST_SUCCESS" ] && { echo "Backup of $(getPoolName "$STORAGE_META_DIR") never succeeded" ; return 1; }
	[ $(( $(getTimestamp) - ( PERIOD*60*60 ) )) -gt "$LAST_SUCCESS" ] && { echo "Last success for backup of $(getPoolName "$STORAGE_META_DIR") older than ${PERIOD}h ($(parseTimestamp "$LAST_SUCCESS")) ${LAST_FAIL_MESSAGE}" ; return 1; }
	return 0;
}


if [ "$MODE" = auto ]
then
	[ -f /etc/storage/autobackup ] || { echo No autobackup configured; exit 1; }
	for C in $(cat /etc/storage/autobackup)
	do
		storage_pool mount "$C" || echo Mounting failed for $STORAGE_META_DIR || continue
		if [ "$(date +%w)" -eq 0 ]
		then
			backup "$C" weekly
		elif [ "$(date +%d)" = "01" ]
		then
			backup "$C" monthly
		else
			backup "$C" daily
		fi
		storage_pool umount "$C" || { echo Mounting failed for $STORAGE_META_DIR; exit 1; }
	done
elif [ "$MODE" = check ]
then
	[ -f /etc/storage/autobackup ] || { echo No autobackup configured; exit 1; }
	RC=0
	for C in $(cat /etc/storage/autobackup)
	do
		MSG=$(check "$C")
		(( OVERALL_RC |= $? ))
		[ "$OVERALL_RC" -ne 0 ] && xmpp "$MSG"
	done
	exit $OVERALL_RC
else
	if checkDevicesAvailable "$STORAGE_META_DIR"
	then
		OVERALL_RC=0
		storage_pool mount "$STORAGE_META_DIR" || { echo Mounting failed for $STORAGE_META_DIR; exit 1; }
		[ "$MODE" = create ] && createBackup "$@"
		[ "$MODE" = add ] && add "$@"
		[ "$MODE" = backup ] && { backup "$@" || { echo Backup failed for $STORAGE_META_DIR; OVERALL_RC=$(( OVERALL_RC |= 1 )); } }

		storage_pool umount "$STORAGE_META_DIR" || { echo Unmounting failed for $STORAGE_META_DIR; exit 1; }
		exit $OVERALL_RC
	else
		echo `date` - Could not backup $STORAGE_META_DIR >> /var/log/dailybackup.log
	fi
fi
