- name: Install software for sway desktop
  package:
    name:
    - sway
    - swayidle
    - fuzzel
    - gnome-keyring
    - otf-font-awesome
    - polkit-gnome
    - pavucontrol
    - pipewire-pulse
    - dex
    - gammastep
    - wf-recorder
    - waybar
    - xdg-desktop-portal-wlr
    - xdg-desktop-portal-gtk
    - qt5ct
    - nemo
    - foot
    - grim
    - slurp
    - wf-recorder
    - swaybg
    - brightnessctl
    - fprintd
    - qt6-wayland
    - blueman
    - dunst
    state: present
  tags:
    - install

- name: Install generic UI components
  package:
    name:
    - gvfs-smb
    - qt5-wayland
    - libgnome-keyring
    - ttf-dejavu
    - swaylock
    - wireplumber
    - otf-font-awesome
    - xorg-xwayland
    state: present
  tags:
    - install
  when: ansible_os_family == "Archlinux"

- name: Install generic UI components
  package:
    name:
    - gvfs-backends
    - qtwayland5
    - ttf-bitstream-vera
    - xwayland
    - wlr-randr
    state: present
  tags:
    - install
  when: ansible_os_family == "Debian"

- name: Create screenrecorder script
  copy:
    src: desktop_sway_screenrecord
    dest: /usr/local/bin/desktop_sway_screenrecord
    mode: '0666'
  tags:
    - config

- name: Configure waybar
  template:
    src: waybar/config.j2
    dest: /etc/xdg/waybar/config
    mode: "0744"
  tags:
    - config

- name: Configure fuzzel
  template:
    src: fuzzel.ini.j2
    dest: /etc/xdg/fuzzel/fuzzel.ini
    mode: "0744"
  tags:
    - config

- name: Start user managers
  systemd:
    name: 'user@{{ users[item].uid }}.service'
    state: started
  loop: "{{ desktop_users }}"
  tags:
    - config

- name: Configure sway
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0744"
  loop:
    - { src: sway/config.j2, dest: /etc/sway/config }
    - { src: sway/00_keybindings.conf.j2, dest: /etc/sway/config.d/00_keybindings.conf }
  tags:
    - config

- name: Session launcher
  template:
    src: sway.sh.j2
    dest: /usr/local/bin/sway-session
    mode: "0644"
  tags:
    - config

- name: Session launcher
  template:
    src: custom-sway.desktop.j2
    dest: /usr/share/wayland-sessions/custom-sway.desktop
  tags:
    - config

- name: Create swaylock PAM config
  copy:
    src: pam/swaylock
    dest: /etc/pam.d/swaylock
    mode: '0644'
  tags:
    - config
