- name: Install software for sway desktop
  package:
    name:
    - sway
    - swayidle
    - fuzzel
    - gnome-keyring
    - pavucontrol
    - pipewire-pulse
    - dex
    - gammastep
    - wf-recorder
    - waybar
    - xdg-desktop-portal-wlr
    - xdg-desktop-portal-gtk
    - qt5ct
    - foot
    - grim
    - slurp
    - wf-recorder
    - swaybg
    - brightnessctl
    - fprintd
    - qt6-wayland
    - blueman
    state: present
  tags:
    - install

- name: Install generic UI components
  package:
    name:
    - pcmanfm-gtk3
    - gvfs-smb
    - qt5-wayland
    - libgnome-keyring
    - ttf-dejavu
    - swaylock
    - wireplumber
    - otf-font-awesome
    - xorg-xwayland
    - otf-font-awesome
    - polkit-gnome
    - fnott
    - wl-mirror
    state: present
  tags:
    - install
  when: ansible_os_family == "Archlinux"

- name: Install generic UI components
  package:
    name:
    - pcmanfm
    - gvfs-backends
    - qtwayland5
    - ttf-bitstream-vera
    - xwayland
    - wlr-randr
    - fonts-font-awesome
    - policykit-1-gnome
    - dunst
    state: present
  tags:
    - install
  when: ansible_os_family == "Debian"

- name: Create screenrecorder script
  template:
    src: desktop_sway_screenrecord.j2
    dest: /usr/local/bin/desktop_sway_screenrecord
    mode: '0755'
  tags:
    - config

- name: Configure waybar
  template:
    src: waybar/config.j2
    dest: /etc/xdg/waybar/config
    mode: "0744"
  tags:
    - config

- name: Configure waybar
  template:
    src: waybar/style.css.j2
    dest: /etc/xdg/waybar/style.css
    mode: "0744"
  tags:
    - config

- name: Configure fuzzel
  template:
    src: fuzzel.ini.j2
    dest: /etc/xdg/fuzzel/fuzzel.ini
    mode: "0744"
  tags:
    - config

- name: Configure foot
  template:
    src: foot.ini.j2
    dest: /etc/xdg/foot/foot.ini
    mode: "0744"
  tags:
    - config

- name: Install fnott
  block:
  - name: Create fnott config dir
    file:
      path: "/etc/xdg/fnott"
      state: directory
    tags:
      - config  

  - name: Configure fnott
    template:
      src: fnott.ini.j2
      dest: /etc/xdg/fnott/fnott.ini
      mode: "0744"
    tags:
      - config
  when: ansible_os_family == "Archlinux"

- name: Configure sway
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0744"
  loop:
    - { src: sway/config.j2, dest: /etc/sway/config }
    - { src: sway/00_keybindings.conf.j2, dest: /etc/sway/config.d/00_keybindings.conf }
  tags:
    - config

- name: Session launcher
  template:
    src: sway.j2
    dest: /usr/local/bin/sway-run
    mode: "0755"
  tags:
    - config

- name: Session launcher
  template:
    src: sway.desktop.j2
    dest: /usr/share/wayland-sessions/sway.desktop
  tags:
    - config

- name: Create swaylock PAM config
  template:
    src: pam/swaylock.j2
    dest: /etc/pam.d/swaylock
    mode: '0644'
  tags:
    - config
