- name: Install GNOME
  package:
    name:
    - gnome-session
    - gnome-shell
    - gnome-settings-daemon
    - gnome-keyring
    - gnome-control-center
    - xdg-desktop-portal-gnome
    - xdg-user-dirs-gtk
    - foot
    state: present
  tags:
    - install
    
- name: Install GNOME
  package:
    name:
    - gvfs-backends
    state: present
  when: ansible_os_family == "Debian"
  tags:
    - install
    
- name: Install GNOME
  package:
    name:
    - gvfs-smb
    - gvfs-mtp
    - gvfs-dnssd
    - gvfs-gphoto2
    - gvfs-afc
    state: present
  when: ansible_os_family == "Archlinux"
  tags:
    - install

- name: Session launcher
  template:
    src: gnome.j2
    dest: /usr/local/bin/gnome-run
    mode: "0755"
  tags:
    - config

- name: Session launcher
  template:
    src: gnome.desktop.j2
    dest: /usr/share/wayland-sessions/gnome.desktop
  tags:
    - config