- name: 'Install'
  package:
    name:
    - php-legacy
    - php-legacy-fpm
    - php-legacy-redis
    - php-legacy-igbinary
    - php-legacy-gd
    - nextcloud
    - pwgen
    - redis
  tags:
    - install

- name: 'Create php config'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    mode: '0660'
  loop:
    - { src: "php/php-fpm.ini.j2", dest: "/etc/php-legacy/php-fpm.ini", user: "root", group: "root" }
    - { src: "php/php-fpm.ini.j2", dest: "/etc/webapps/nextcloud/php.ini", user: "{{ nextcloud_user }}", group: "{{ nextcloud_group}}" }
  tags:
    - config

- name: Configure directories
  file:
    path: '{{ item.path }}'
    owner: '{{ nextcloud_user }}'
    mode: '{{ item.mode }}'
    state: directory
  loop:
   - { path: '/var/lib/nextcloud', mode: '0755' }
   - { path: '/var/lib/nextcloud/apps', mode: '0755' }
   - { path: '/var/lib/nextcloud/data', mode: '0770' }
   - { path: '/var/lib/nextcloud/sessions', mode: '0700' }

- user:
    name: nextcloud
    groups: webshare
    append: yes

- name: 'Enable services'
  systemd:
    name: "{{ item }}"
    enabled: yes
  loop:
    - redis
  tags:
    - config