- name: 'Install'
  package:
    name:
    - php-legacy
    - php-legacy-fpm
    - php-legacy-redis
    - php-legacy-igbinary
    - php-legacy-gd
    - nextcloud
    - pwgen
    - redis
    state: present
  tags:
    - install

- name: Allow install in config
  lineinfile:
    path: "/etc/redis/redis.conf"
    line: "supervised auto"

- name: Configure directories
  file:
    path: '{{ item.path }}'
    owner: '{{ nextcloud_user }}'
    mode: '{{ item.mode }}'
    state: directory
  loop:
   - { path: '/var/lib/nextcloud', mode: '0755' }
   - { path: '/var/lib/nextcloud/apps', mode: '0755' }
   - { path: '/var/lib/nextcloud/data', mode: '0770' }
   - { path: '/var/lib/nextcloud/sessions', mode: '0700' }

- user:
    name: nextcloud
    groups: webshare
    append: yes

- name: 'Enable services'
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: "started"
  loop:
    - redis
  tags:
    - config