#!/bin/bash

read -sp 'Enter vault password ' PASS

[ -d "credentials_encfs" ] && echo "$PASS" | encfs -o nonempty --stdinpass "$(realpath credentials_encfs)" "$(realpath credentials)" || exit 1

find credentials -name "*ansible_lockfile" -delete
echo
read -p 'Hit any key to unmount'

[ -d "credentials_encfs" ] && encfs -u credentials
