#!/bin/bash

[ -e "production" ] || { echo This expects a production inventory to exist, have a look at the README.md && exit 1; }

[ -e "secret.yml" ] && read -sp 'Enter vault password ' PASS

[ -e "production_hosts" ] && PRODUCTION_HOSTS="-i production_hosts"

SECRETS=""

if [ -e "secret.yml" ]
then
	echo "$PASS" | ansible-playbook $PRODUCTION_HOSTS -i production site.yml --skip-tags upgrade -e@secret.yml --vault-password-file <(echo "$PASS") -l $@
else
	echo "$PASS" | ansible-playbook $PRODUCTION_HOSTS -i production site.yml --skip-tags upgrade -l $@
fi
