- hosts: server_dns
  become: yes
  roles:
  - server-dns

- hosts: staging_fakeca
  become: yes
  roles:
    - client-fakeca

- hosts: all
  become: yes
  roles:
  - hosts
  - ansible-deps
  - common

- hosts: server_pacman_repo
  become: yes
  roles:
  - server-pacman-repo

- hosts: builder_pacman_repo
  become: yes
  roles:
  - pacman-repo-builder

- hosts: arch
  become: yes
  roles:
  - common-arch

- hosts: debian
  become: yes
  roles:
  - common-debian


- hosts: server_teamspeak
  become: yes
  roles:
  - server-backup
  - server-teamspeak

- hosts: server_syncplay
  become: yes
  roles:
  - server-backup
  - server-syncplay

  
- hosts: server_remotely
  become: yes
  roles:
  - server-remotely

- hosts: server_arch
  become: yes
  roles:
  - pacmatic
  
- hosts: server
  become: yes
  roles:
  - server-sshtunnel
  - server-backup
  - server-nginx-base
  - server-letsencrypt
  - server-nginx
  - server-mariadb
  - server-turn
  - server-webdav
  - server-nextcloud
  - server-prosody
  - server-jabber
  - server-jitsi-meet
  - server-mail
  - server-sogo
  - server-fail2ban
  - util-run-letsencrypt-hooks

- hosts: ufw
  become: yes
  roles:
  - ufw

- hosts: testclient
  become: yes
  roles:
  - testclient-common
  - testclient-jabber

- hosts: desktop_arch
  become: yes
  roles:
  - aurhelper

- hosts: desktop
  become: yes
  roles:
  - X11
  - desktop
  - desktop-cinnamon
  - default-apps

