- hosts: server_dns
  become: yes
  roles:
  - util-package-upgrade
  - server-dns

- hosts: staging_fakeca
  become: yes
  roles:
  - util-package-upgrade
  - client-fakeca

- hosts: server_pacman_repo
  become: yes
  roles:
  - util-package-upgrade
  - server-pacman-repo

- hosts: builder_pacman_repo
  become: yes
  roles:
  - util-package-upgrade
  - pacman-repo-builder

- hosts: all
  become: yes
  roles:
  - custom-repos

- hosts: arch
  become: yes
  roles:
  - common-arch

- hosts: debian
  become: yes
  roles:
  - common-debian

- hosts: all
  become: yes
  roles:
  - common

- hosts: all
  become: yes
  roles:
  - hosts
  - ansible-deps

- hosts: staging_local
  become: yes
  remote_user: admin
  roles:
    - users

- hosts: staging_local
  become: yes
  remote_user: admin
  roles:
    - users

- hosts: local
  become: yes
  remote_user: admin
  roles:
  - users

- hosts: nas
  become: yes
  remote_user: admin
  roles:
  - users
  - server-samba

- hosts: server_teamspeak
  become: yes
  roles:
  - server-backup
  - server-teamspeak

- hosts: server_syncplay
  become: yes
  roles:
  - server-backup
  - server-syncplay

  
- hosts: server_remotely
  become: yes
  roles:
  - server-remotely

- hosts: server_arch
  become: yes
  
- hosts: server
  become: yes
  roles:
  - server-sshtunnel
  - server-backup
  - server-nginx-base
  - server-letsencrypt
  - server-nginx
  - server-mariadb
  - server-turn
  - server-webdav
  - server-nextcloud
  - server-prosody
  - server-jabber
  - server-jitsi-meet
  - server-mail
  - server-sogo
  - server-fail2ban
  - util-run-letsencrypt-hooks
  
- hosts: server_games
  become: yes
  roles:
  - server-backup
  - server-linuxgsm

- hosts: ufw
  become: yes
  roles:
  - ufw

- hosts: testclient
  become: yes
  roles:
  - testclient-common
  - testclient-jabber
  - testclient-sogo
  - testclient-jitsi

- hosts: desktop_arch
  become: yes
  roles:
  - aurhelper

- hosts: desktop
  become: yes
  roles:
  - X11
  - kernel-zen
  - kernel
  - automount
  - desktop
  - desktop-cinnamon
  - desktop-sway
  - default-apps

