- name: Install generic UI components
  package:
    name:
      - ly
    state: present
  when: ansible_os_family == "Archlinux"
  tags:
    - install


- name: enable desktop manager
  systemd:
    name: ly
    enabled: yes
    state: started
  tags:
    - config
  when: ansible_os_family == "Archlinux"

- name: Install generic UI components
  package:
    name:
      - gdm3
    state: present
  tags:
    - install
  when: ansible_os_family == "Debian"

- name: enable desktop manager
  systemd:
    name: gdm
    enabled: yes
  tags:
    - config
  when: ansible_os_family == "Debian"

- name: Install sound support
  package:
    name:
      - alsa-utils
      - wireplumber
    state: present
  tags:
    - install

- name: Create ly PAM config
  copy:
    src: pam/ly
    dest: /etc/pam.d/ly
    mode: '0644'
  when: ansible_os_family == "Archlinux"
  tags:
    - config

- name: Create ly config
  copy:
    src: ly/config.ini
    dest: /etc/ly/config.ini
    mode: '0644'
  when: ansible_os_family == "Archlinux"
  tags:
    - config

- name: 'Configure system for lower latency'
  copy:
    src: "latency.conf"
    dest: '/etc/tmpfiles.d/latency.conf'
    mode: '0644'
  tags:
    - config
