- name: Install generic UI components
  package:
    name:
      - greetd-regreet
    state: present
  when: ansible_os_family == "Archlinux"
  tags:
    - install

- name: enable desktop manager
  systemd:
    name: greetd
    enabled: yes
    state: started
  tags:
    - config
  when: ansible_os_family == "Archlinux"

- name: Install generic UI components
  package:
    name:
      - gdm3
    state: present
  tags:
    - install
  when: ansible_os_family == "Debian"

- name: enable desktop manager
  systemd:
    name: gdm
    enabled: yes
  tags:
    - config
  when: ansible_os_family == "Debian"

- name: Install sound support
  package:
    name:
      - alsa-utils
      - wireplumber
    state: present
  tags:
    - install

- name: Create greetd PAM config
  copy:
    src: pam/greetd
    dest: /etc/pam.d/greetd
    mode: '0644'
  when: ansible_os_family == "Archlinux"
  tags:
    - config

- name: Create greetd config directories
  file:
    state: directory
    dest: "/etc/greetd/sway.d"
    mode: '0755'
  when: ansible_os_family == "Archlinux"
  tags:
    - config

- name: Create greetd config
  template:
    src: "greetd/{{ item }}.j2"
    dest: "/etc/greetd/{{ item }}"
    mode: '0644'
  when: ansible_os_family == "Archlinux"
  loop:
    - config.toml
    - regreet.toml
    - sway.conf
  tags:
    - config

- name: 'Configure system for lower latency'
  copy:
    src: "latency.conf"
    dest: '/etc/tmpfiles.d/latency.conf'
    mode: '0644'
  tags:
    - config
