- name: 'Create pacman config'
  template:
    src: "pacman.conf.j2"
    dest: "/etc/pacman.conf"
    mode: '0644'
  when: ansible_os_family == "Archlinux"
  tags:
    - config

- name: 'Create mirrorlist'
  template:
    src: "mirrorlist.j2"
    dest: "/etc/pacman.d/mirrorlist"
    mode: '0644'
  when: pacman_mirrorlist is defined and ansible_os_family == "Archlinux"
  tags:
    - config

- name: Update Databases
  shell: pacman -Sy
  when: ansible_os_family == "Archlinux"
  tags:
    - install
