- name: 'Install'
  pacman:
    name:
    - pacmatic
    - s-nail
  tags:
    - install
    
- name: 'Create service'
  template:
    src: pacmatic.service.j2
    dest: '/etc/systemd/system/pacmatic.service'
    mode: '0644'
  register: systemd
  tags:
    - config
    
- name: 'Create timer'
  template:
    src: pacmatic.timer.j2
    dest: '/etc/systemd/system/pacmatic.timer'
    mode: '0644'
  register: systemd
  tags:
    - config

- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: systemd.changed
  tags:
    - config

- name: 'Start timer'
  systemd:
    name: 'pacmatic.timer'
    enabled: true
    state: started
  tags:
    - config
