- name: Install zen kernel
  pacman:
    name:
    - linux-zen
    - linux-zen-headers
  tags:
    - install

- name: Detect systemd loader
  stat:
    path: /boot/loader
  register: systemd_loader_folder

- name: Config systemd loader
  block:
  - name: Copy loader file for systemd boot
    copy:
      src: /boot/loader/entries/arch-lts.conf
      dest: /boot/loader/entries/arch-zen.conf
      remote_src: yes
    tags:
      - config

  - lineinfile:
      path: /boot/loader/entries/arch-zen.conf
      regexp: 'linux /vmlinuz-linux'
      line: 'linux /vmlinuz-linux-zen'
    tags:
      - config

  - lineinfile:
      path: /boot/loader/entries/arch-zen.conf
      regexp: 'title'
      line: 'Arch Linux Zen'
    tags:
      - config

  - lineinfile:
      path: /boot/loader/entries/arch-zen.conf
      regexp: 'initrd /initramfs-linux.img'
      line: 'initrd /initramfs-linux-zen.img'
    tags:
      - config
  when: systemd_loader_folder.stat.exists

- name: Detect grub
  stat:
    path: /boot/grub/grub.cfg
  register: grub_config_file
  
- name: Reconfig grub
  shell:
    cmd: "grub-mkconfig -o /boot/grub/grub.cfg"
  when: grub_config_file.stat.exists
