- name: Install wireless support
  package:
    name:
    - iw
    - wireless-regdb
    - bluez
  tags:
    - install

- name: Install wireless support
  package:
    name:
    - wpa_supplicant
    - networkmanager
    - bluez-utils
  when: ansible_os_family == "Archlinux"
  tags:
    - install

- name: Install wireless support
  package:
    name:
    - wpasupplicant
    - network-manager
    - bluez-tools
  when: ansible_os_family == "Debian"
  tags:
    - install

- name: Enable NetworkManager service
  systemd:
    name: NetworkManager
    enabled: yes
    state: started
  tags:
    - config

- name: Enable Bluetooth service
  systemd:
    name: bluetooth
    enabled: yes
    state: started
  tags:
    - config

- name: 'Create regulatory domain config'
  template:
    src: wireless-regdom.j2
    dest: '/etc/conf.d/wireless-regdom'
    mode: '0644'
  when: ansible_os_family == "Archlinux"
  tags:
    - config

- name: 'Create regulatory domain config'
  copy:
    content: "{{ wireless_regulatory_domain | default('00') }}"
    dest: '/etc/default/crda'
    mode: '0644'
  when: ansible_os_family == "Debian"
  tags:
    - config
