- name: Install
  package:
    name: samba
  register: samba_install
  notify: restart_samba
  tags:
    - install
    - upgrade

- name: 'Create config'
  template:
    src: smb.conf.j2
    dest: '/etc/samba/smb.conf'
    mode: '0700'
  register: samba_config
  notify: reload_samba
  tags:
    - config
