- name: Install
  package:
    name: samba
    state: present
  register: samba_install
  notify: restart_samba
  tags:
    - install

- name: 'Create config'
  template:
    src: smb.conf.j2
    dest: '/etc/samba/smb.conf'
    mode: '0700'
  register: samba_config
  notify: reload_samba
  tags:
    - config

- name: "Create samba users"
  ansible.builtin.shell: >
    set -e -o pipefail
    && (pdbedit --user={{ item.username }} 2>&1 > /dev/null)
    || (echo '{{ item.password }}'; echo '{{ item.password }}')
    | smbpasswd -a -s {{ item.username }}
  args:
    executable: /bin/bash
  register: samba_create_users
  changed_when: "'Added user' in samba_create_users.stdout"
  loop: "{{ server_samba_users }}"
  when: server_samba_users is defined

- name: shell - set samba passwords correctly
  ansible.builtin.shell: >
    set -e -o pipefail
    && (smbclient -U {{ item.username }}%{{ item.password }} -L 127.0.0.1 2>&1 > /dev/null)
    || (echo '{{ item.password }}'; echo '{{ item.password }}')
    | smbpasswd {{ item.username }}
  args:
    executable: /bin/bash
  register: samba_verify_users
  changed_when: "'New SMB password' in samba_verify_users.stdout"
  loop: "{{ server_samba_users }}"
  when: server_samba_users is defined
