- name: Storage scripts
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    mode: u=rx,g=rx,o=rx
  loop: "{{ lookup('fileglob', 'scripts/*', wantlist=True) }}"

- name: Configure directories
  file:
    path: "{{ item }}"
    mode: '0755'
    state: directory
  loop:
    - /etc/snapper/config-templates
  tags:
    - config

- name: Snapper template
  copy:
    src: "snapraid"
    dest: /etc/snapper/config-templates/snapraid
    mode: u=rw,g=r,o=r

- name: Create temporary file
  tempfile:
    state: file
  register: download_repo

- name: 'Get index.html'
  get_url:
    url: 'https://github.com/automorphism88/snapraid-btrfs/tags'
    dest: '{{ download_repo.path }}'
    force: yes
  when: download_repo.path is defined

- name: Determine latest available version
  shell: 'grep -Eo "v[0-9]+\.[0-9]+\.[0-9]+" {{ download_repo.path }} | sort -uV | tail -n1'
  register: latest_determined
  when: download_repo.path is defined

- name: Remove temporary file
  file:
    path: "{{ download_repo.path }}"
    state: absent
  when: download_repo.path is defined

- name: Check installed version
  stat:
    path: '/opt/snapraid-btrfs/latest'
  register: latest_stat

- name: Set latest installed version 
  set_fact:
    latest_installed: '{{ latest_stat.stat.lnk_target | basename }}'
  when: latest_stat.stat.exists is defined and latest_stat.stat.exists == true

- name: Upgrade snapraid-btrfs
  block:
    - name: 'Create destination for version {{ latest_determined.stdout }}'
      file:
        path: '/opt/snapraid-btrfs/{{ latest_determined.stdout }}'
        state: directory
        mode: '0755'
      when: latest_determined.stdout is defined

    - name: 'Deploy snapraid-btrfs {{ latest_determined.stdout }}'
      unarchive:
        src: 'https://github.com/automorphism88/snapraid-btrfs/archive/refs/tags/{{ latest_determined.stdout }}.tar.gz'
        dest: '/opt/snapraid-btrfs/{{ latest_determined.stdout }}'
        remote_src: yes
        extra_opts: [--strip-components=1]
      when: latest_determined.stdout is defined

    - name: 'Set symlink'
      file:
        src: '/opt/snapraid-btrfs/{{ latest_determined.stdout }}/snapraid-btrfs'
        dest: '/opt/snapraid-btrfs/snapraid-btrfs'
        state: link
        force: yes
      when: latest_determined.stdout is defined

  when: (latest_stat.stat.exists is defined and latest_stat.stat.exists == false) or (latest_determined.stdout is defined and latest_installed is defined and latest_determined.stdout is version(latest_installed, ">"))

- name: 'Create services'
  copy:
    src: "{{ item }}"
    dest: '/etc/systemd/system/{{ item }}'
    mode: '0644'
  loop:
    - storage-maintenance-full.service
    - storage-maintenance-full.timer
    - storage-maintenance-mini.service
    - storage-maintenance-mini.timer
    - storage-backup.service
    - storage-backup.timer
    - storage-mount.service
  register: systemd

- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: systemd.changed
  tags:
    - systemd

- name: 'Start services'
  systemd:
    name: '{{ item }}'
    enabled: yes
    state: started
  loop:
    - storage-maintenance-full.timer
    - storage-maintenance-mini.timer
    - storage-backup.timer
  tags:
    - config

- name: Create configuration directory
  file:
    path: "/etc/storage/maintenance"
    state: directory
  tags:
    - config
