version: '3'

services:
  staging-repo-arch:
    build: archbase/
    image: archbase:latest
    cap_add:
      - SYS_ADMIN
    networks:
      staging_net:
        ipv4_address: 172.28.0.10
        ipv6_address: "fe81::172:28:0:10"
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - archrepodata:/var/lib/pacman-repo/packages
      - archbuilddatapkgs:/var/lib/pacman-repo-builder/pkgs
      - archbuilddatarepo:/var/lib/pacman-repo-builder/repo
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      
  staging-dns-arch:
    build: archbase/
    image: archbase:latest
    cap_add:
      - SYS_ADMIN
    networks:
      staging_net:
        ipv4_address: 172.28.0.15
        ipv6_address: "fe81::172:28:0:15"
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      
  staging-dns-debian:
    build: debianbase/
    image: debianbase:latest
    cap_add:
      - SYS_ADMIN
    networks:
      staging_net:
        ipv4_address: 172.28.0.16
        ipv6_address: "fe81::172:28:0:16"
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  staging-server-arch:
    build: archbase/
    image: archbase:latest
    cap_add:
      - SYS_ADMIN
    networks:
      staging_net:
        ipv4_address: 172.28.0.11
        ipv6_address: "fe81::172:28:0:11"
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  staging-server-debian:
    build: debianbase/
    image: debianbase:latest
    cap_add:
      - SYS_ADMIN
    networks:
      staging_net:
        ipv4_address: 172.28.0.12
        ipv6_address: "fe81::172:28:0:12"
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  staging-desktop-arch:
    build: archvnc/
    image: archvnc:latest
    cap_add:
      - SYS_ADMIN
    networks:
      staging_net:
        ipv4_address: 172.28.0.13
        ipv6_address: "fe81::172:28:0:13"
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - testclientdata:/var/lib/testclient
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    
  staging-desktop-debian:
    build: debianvnc/
    image: debianvnc:latest
    cap_add:
      - SYS_ADMIN
    networks:
      staging_net:
        ipv4_address: 172.28.0.14
        ipv6_address: "fe81::172:28:0:14"
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - testclientdata:/var/lib/testclient
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  staging-testclient-arch:
    build: archvnc/
    image: archvnc:latest
    cap_add:
      - SYS_ADMIN
    networks:
      staging_net:
        ipv4_address: 172.28.0.17
        ipv6_address: "fe81::172:28:0:17"
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - testclientdata:/var/lib/testclient
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    
  staging-testclient-debian:
    build: debianvnc/
    image: debianvnc:latest
    cap_add:
      - SYS_ADMIN
    networks:
      staging_net:
        ipv4_address: 172.28.0.18
        ipv6_address: "fe81::172:28:0:18"
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - testclientdata:/var/lib/testclient
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

networks:
  staging_net:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
        - subnet: "fe81::/16"
        
volumes:
  archrepodata:
  archbuilddatapkgs:
  archbuilddatarepo:
  testclientdata:
