- name: 'Install dependencies'
  package:
    name:
    - restic
    state: present
  tags:
    - install

- name: 'Create script'
  template:
    src: restic-backup.j2
    dest: '/usr/local/bin/restic-backup'
    mode: '0700'
  tags:
    - config

- name: Configure directories
  file:
    path: "{{ item }}"
    mode: '0700'
    state: directory
  loop:
    - '/etc/restic-backup/'
  tags:
    - config

- name: 'Create service'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0700'
  register: systemd
  loop:
    - { src: "restic-backup.service.j2", dest: "/etc/systemd/system/restic-backup.service" }
    - { src: "restic-backup.timer.j2", dest: "/etc/systemd/system/restic-backup.timer" }
  tags:
    - config

- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: systemd.changed
  tags:
    - config

- name: 'Start service'
  systemd:
    name: 'restic-backup.timer'
    enabled: yes
    state: started
  tags:
    - config

- name: "Create configurations"
  template:
    src: "conf.j2"
    dest: "/etc/restic-backup/{{ item.id }}.conf"
    mode: '0700'
  register: systemd
  loop: "{{ restic_backup_configs }}"
  when: restic_backup_configs is defined
  tags:
    - config

