nextcloud_path: /var/www/nextcloud
nextcloud_rw_path: /var/lib/nextcloud
nextcloud_data_path: "{{ nextcloud_rw_path }}/data"
nextcloud_session_path: "{{ nextcloud_rw_path }}//sessions"
nextcloud_apps_path: "{{ nextcloud_rw_path }}//apps"
nextcloud_config_dir: /var/www/nextcloud/config
nextcloud_config_path: "{{ nextcloud_config_dir }}/config.php"
nextcloud_config_path_ro: "{{ nextcloud_config_dir }}/onfig.php"
nextcloud_user: www-data
nextcloud_group: www-data
php_command: php
php_fpm_path: /etc/php/8.2/fpm
php_path: "{{ php_fpm_path }}"
php_ini_path: "{{ php_fpm_path }}/php.ini"
nextcloud_php_config_path: "{{ php_ini_path }}"
php_fpm_service: "php8.2-fpm"
php_modules: "/var/lib/php/modules/8.2/fpm/enabled_by_maint"
nextcloud_fastcgi: "unix://run/php/php8.2-fpm.sock"
