- name: 'Install'
  kewlfft.aur.aur:
    name:
    - sogo
  become: yes
  become_user: aur_builder
  tags:
    - install
    
- name: 'Install nginx - WORKAROUND'
  kewlfft.aur.aur:
    name:
    - nginx-mod-njs
  become: yes
  become_user: aur_builder
  tags:
    - install
