- name: Time settings
  timezone:
    name: Europe/Berlin
    hwclock: UTC

- name: Set locale
  locale_gen:
    name: "{{ locales }}"
    state: present

- name: create locale.conf
  file:
    path: /etc/locale.conf
    state: touch

- name: locale.conf file
  lineinfile:
    path: /etc/locale.conf
    regex: "^LANG="
    line: "LANG={{ locales[0] }}"

- name: create vconsole.conf
  file:
    path: /etc/vconsole.conf
    state: touch

- name: vconsole.conf file
  lineinfile:
    path: /etc/vconsole.conf
    regex: "^KEYMAP="
    line: "KEYMAP={{ keymap }}"

- name: Utilites
  package:
    name:
      - bash-completion
    state: present
  tags:
    - install

- name: Install console utilities
  package:
    name:
      - tmux
      - mosh
      - wget
      - htop
      - iotop
      - rsync
      - time
      - net-tools
    state: present
  tags:
    - install

- name: Put a .local/bin/ folder in each home on the path
  copy:
    src: files/homebin/homebin.sh
    dest: /etc/profile.d/homebin.sh
  tags:
    - config

- name: Config editor
  lineinfile:
    path: /etc/environment
    line: EDITOR={{ environment_editor | default('nano') }}

- name: Config less
  lineinfile:
    path: /etc/environment
    line: LESS={{ environment_less | default('--mouse --wheel-lines=3') }}

- name: Configure tools
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - { src: "files/tmux/tmux.conf", dest: "/etc/tmux.conf" }
    - { src: "files/nano/nanorc", dest: "/etc/nanorc" }
    - { src: "files/htop/htoprc", dest: "/etc/htoprc" }
  tags:
    - config

- name: 'Enable services'
  systemd:
    name: "systemd-timesyncd"
    enabled: yes
    state: restarted
  tags:
    - config
