- name: Add 32 bit architecture
  command: dpkg --add-architecture i386
  when: debian_multiarch is true
  
- include_role:
    name: util-package-upgrade

- name: Utilites
  package:
    name:
      - build-essential
  tags:
    - install
