domain: "staging.arch"
hostname: "staging-nas-arch"
fqdn: "{{ hostname }}.{{ domain }}"
public_ip_v4: "{{ netconf[hostname].ip_v4 }}"
public_ip_v6: "{{ netconf[hostname].ip_v6 }}"

locales:
  - en_US.UTF-8
keymap: en

letsencrypt_mail: "hostmaster@{{ domain }}"
letsencrypt_port: "8000"
letsencrypt_fake: true

hosts_entries:
  - name: staging-repo-arch
    ip: "{{ hostvars['staging-repo-arch'].public_ip_v4 }}"
    domain: staging.arch
    subdomains:
      - repo
    aliases:
    - repo-arch

users:
  user:
    password: $6$user$.0YKoey4twE3UDoG7VwhMgDXK0hnQqYHSJWlWOSICaAGRMchCbs4eDGHJgU8HFe.xtN0sUEyfS50QPjuRmVg91
    groups:
    uid: 2000
    fullname: Test User
    mail: testuser@{{ domain }}

server_samba_users:
  - username: user
    password: "{{ lookup('password', 'credentials/{{ fqdn }}/samba/user length=12') }}"

server_samba_shares:
  - name: testshare
    path: /tmp
    validusers:
      - user
  - name: testshare-guest
    path: /tmp
    guestok: "yes"
  - name: testshare-guest-ro
    path: /tmp
    readonly: "yes"
    guestok: "yes"

backup_server_path: "/tmp"
restore_server_path: "{{ backup_server_path}}"

server_nginx_user: "http"
server_nginx_group: "http"
server_nginx_port_https_backend: "4444"
server_nginx_port_https_backend_proxy: "4445"
server_nginx_port_http: "80"
server_nginx_port_tls: "443"
server_nginx_port_tls_no_pp: "4440"
server_nginx_default_domains:
  - "{{ domain }}"
