domain: "staging.arch"
hostname: "staging-desktop-arch"
fqdn: "{{ hostname }}.{{ domain }}"


locales:
  - en_US.UTF-8
keymaps:
  - en-latin1-nodeadkeys

pacman_repos:
  - name: "core"
    include: "/etc/pacman.d/mirrorlist"
  - name: "extra"
    include: "/etc/pacman.d/mirrorlist"
  - name: "community"
    include: "/etc/pacman.d/mirrorlist"
  - name: "multilib"
    include: "/etc/pacman.d/mirrorlist"
  - name: "testrepo"
    server: "https://repo.staging.arch"
    siglevel: Optional

letsencrypt_fake: true

server_subdomains:
  - turn
  - meet
  - xmpp
  - nextcloud
  - sogo
  - webdav
  - xmpp
  - remotely
  - mail

#hosts_entries:
#  - ip: "123.123.123.1"
#    hostnames: "canonical alias1 alias2"

hosts_entries:
  - name: staging-server-arch
    ip: "{{ hostvars['staging-server-arch'].public_ip_v4 }}"
    domain: staging.arch
    subdomains: "{{ server_subdomains }}"
    aliases:
    - server-arch
  - name: staging-repo-arch
    ip: "{{ hostvars['staging-repo-arch'].public_ip_v4 }}"
    domain: staging.arch
    subdomains:
      - repo
    aliases:
    - repo-arch
  - name: staging-server-debian
    ip: "{{ hostvars['staging-server-debian'].public_ip_v4 }}"
    domain: staging.debian
    subdomains: "{{ server_subdomains }}"
    aliases:
    - server-debian

automount_credentials:
  - username: tester
    password: "{{ lookup('password', 'credentials/{{ fqdn }}/samba/tester length=12') }}"

automount_mounts:
  - escapedname: "media-testshare"
    src: "//staging-nas-arch/testshare"
    path: "/media/testshare"
    type: "cifs"
    host: "staging-nas-arch"
    mac: "11:22:33:44:55:66"
  - escapedname: "media-testshare_guest"
    src: "//staging-nas-arch/testshare-guest"
    path: "/media/testshare_guest"
    type: "cifs"
  - escapedname: "media-testshare_guest_ro"
    src: "//staging-nas-arch/testshare-guest-ro"
    path: "/media/testshare_guest_ro"
    type: "cifs"
