domain: "staging.arch"
hostname: "staging-testclient-arch"
fqdn: "{{ hostname }}.{{ domain }}"

java_home: "/usr/lib/jvm/default"

locales:
  - en_US.UTF-8
keymap: en

letsencrypt_fake: true

hosts_entries:
  - name: staging-repo-arch
    ip: "{{ hostvars['staging-repo-arch'].public_ip_v4 }}"
    domain: staging.arch
    subdomains:
      - repo
    aliases:
    - repo-arch
