domain: "staging.arch"
hostname: "staging-gameserver-arch"
fqdn: "{{ hostname }}.{{ domain }}"

public_ip_v4: "{{ netconf[hostname].ip_v4 }}"
public_ip_v6: "{{ netconf[hostname].ip_v6 }}"

locales:
  - en_US.UTF-8
keymaps:
  - en-latin1-nodeadkeys
  
letsencrypt_fake: true

pacman_repos:
  - name: "core"
    include: "/etc/pacman.d/mirrorlist"
  - name: "extra"
    include: "/etc/pacman.d/mirrorlist"
  - name: "community"
    include: "/etc/pacman.d/mirrorlist"
  - name: "multilib"
    include: "/etc/pacman.d/mirrorlist"
  - name: "testrepo"
    server: "https://repo.staging.arch"
    siglevel: Optional

hosts_entries:
  - name: staging-repo-arch
    ip: "{{ hostvars['staging-repo-arch'].public_ip_v4 }}"
    domain: staging.arch
    subdomains:
      - repo
    aliases:
    - repo-arch

testadmin_pwd: "admin"
testuser_pwd: "tester"

server_pacmanrepo_name: "testrepo"

backup_server_path: "/tmp"
restore_server_path: "{{ backup_server_path}}"

linuxgsm_servers:
  - id: valheim_test
    type: vhserver
    config: |
        servername="{{ domain }} Valheim server"
        serverpassword="{{testuser_pwd }}"
        gameworld="vhserver"
        port="2456"
    dependencies:
      - lib32-sdl2
      - bc
      - jq
    backup:
      - /opt/linuxgsm/valheim_test/.config/unity3d/IronGate/Valheim/worlds
    ports:
      - {port: "2456", proto: "udp"}
      - {port: "2457", proto: "udp"}
