domain: "staging.debian"
hostname: "staging-nas-debian"
fqdn: "{{ hostname }}.{{ domain }}"
public_ip_v4: "{{ netconf[hostname].ip_v4 }}"
public_ip_v6: "{{ netconf[hostname].ip_v6 }}"

locales:
  - en_US.UTF-8
keymap: en

users:
  user:
    password: $6$user$.0YKoey4twE3UDoG7VwhMgDXK0hnQqYHSJWlWOSICaAGRMchCbs4eDGHJgU8HFe.xtN0sUEyfS50QPjuRmVg91
    groups:
    uid: 2000
    fullname: Test User
    mail: testuser@{{ domain }}

server_samba_shares:
  - name: testshare
    path: /tmp
    validusers:
      - user
  - name: testshare-guest
    path: /tmp
    guestok: "yes"
  - name: testshare-guest-ro
    path: /tmp
    readonly: "yes"
    guestok: "yes"

letsencrypt_fake: true
