domain: "staging.arch"
hostname: "staging-desktop-arch"
fqdn: "{{ hostname }}.{{ domain }}"


locales:
  - en_US.UTF-8
keymaps:
  - en-latin1-nodeadkeys

pacman_repos:
  - name: "testrepo"
    server: "https://repo.staging.arch"
    siglevel: Optional
  - name: "multilib"
    include: "/etc/pacman.d/mirrorlist"

letsencrypt_fake: true

server_subdomains:
  - turn
  - meet
  - xmpp
  - nextcloud
  - sogo
  - webdav
  - xmpp
  - remotely
  - mail

hosts_entries:
  - name: staging-server-arch
    ip: "{{ hostvars['staging-server-arch'].public_ip_v4 }}"
    domain: staging.arch
    subdomains: "{{ server_subdomains }}"
    aliases:
    - server-arch
  - name: staging-repo-arch
    ip: "{{ hostvars['staging-repo-arch'].public_ip_v4 }}"
    domain: staging.arch
    subdomains:
      - repo
    aliases:
    - repo-arch
  - name: staging-server-debian
    ip: "{{ hostvars['staging-server-debian'].public_ip_v4 }}"
    domain: staging.debian
    subdomains: "{{ server_subdomains }}"
    aliases:
    - server-debian

#hosts_entries:
#  - ip: "123.123.123.1"
#    hostnames: "canonical alias1 alias2"

