domain: "staging.arch"
hostname: "staging-desktop-arch"
fqdn: "{{ hostname }}.{{ domain }}"

server_subdomains:
  - turn
  - meet
  - xmpp
  - nextcloud
  - sogo
  - webdav
  - remotely

hosts_entries:
  - name: staging-server-arch
    ip: "{{ hostvars['staging-server-arch'].public_ip_v4 }}"
    domain: staging.arch
    subdomains: "{{ server_subdomains }}"
    aliases:
    - server-arch
  - name: staging-server-debian
    ip: "{{ hostvars['staging-server-debian'].public_ip_v4 }}"
    domain: staging.debian
    subdomains: "{{ server_subdomains }}"
    aliases:
    - server-debian

pacman_repos:
  - name: "multilib"
    include: "/etc/pacman.d/mirrorlist"

#hosts_entries:
#  - ip: "123.123.123.1"
#    hostnames: "canonical alias1 alias2"

