domain: "staging.debian"
hostname: "staging-desktop-debian"
fqdn: "{{ hostname }}.{{ domain }}"

locales:
  - en_US.UTF-8
keymaps:
  - en-latin1-nodeadkeys

letsencrypt_fake: true

server_subdomains:
  - turn
  - meet
  - xmpp
  - nextcloud
  - sogo
  - webdav
  - xmpp
  - remotely
  - mail

#hosts_entries:
#  - ip: "123.123.123.1"
#    hostnames: "canonical alias1 alias2"

hosts_entries:
  - name: staging-server-arch
    ip: "{{ hostvars['staging-server-arch'].public_ip_v4 }}"
    domain: staging.arch
    subdomains: "{{ server_subdomains }}"
    aliases:
    - server-arch
  - name: staging-server-debian
    ip: "{{ hostvars['staging-server-debian'].public_ip_v4 }}"
    domain: staging.debian
    subdomains: "{{ server_subdomains }}"
    aliases:
    - server-debian

automount_credentials:
  - username: tester
    password: "{{ lookup('password', 'credentials/staging-nas-debian.staging.debian/samba/tester length=12') }}"

automount_onlinechecks:
  - "staging-nas-debian"

automount_mounts:
  - escapedname: "media-testshare"
    src: "//staging-nas-debian/testshare"
    path: "/media/testshare"
    type: "cifs"
    waitfor: "staging-nas-debian"
  - escapedname: "media-testshare_guest"
    src: "//staging-nas-debian/testshare-guest"
    path: "/media/testshare_guest"
    type: "cifs"
    waitfor: "staging-nas-debian"
  - escapedname: "media-testshare_guest_ro"
    src: "//staging-nas-debian/testshare-guest-ro"
    path: "/media/testshare_guest_ro"
    type: "cifs"
    waitfor: "staging-nas-debian"
