- name: Install syncthing
  package:
    name: syncthing
    state: present
  tags:
    - install
  
- name: Enable syncthing per user
  systemd:
    name: syncthing@{{item}}
    state: started
    enabled: yes
  loop: "{{ desktop_users }}"
  when: desktop_users is defined
  tags:
    - config
