- name: Install syncthing
  package:
    name: syncthing
    state: present
  tags:
    - install
  
- name: Enable syncthing per user
  systemd:
    name: syncthing@{{item}}
    state: started
    enabled: yes
  loop: "{{ syncthing_users }}"
  when: syncthing_users is defined
  tags:
    - config
