- name: restart_samba
  systemd:
    name: '{{ item }}'
    state: restarted
  loop:
    - "{{ samba_smb_service | default('smb') }}"
    - "{{ samba_nmb_service | default('nmb') }}"
  when: samba_install.changed

- name: reload_samba
  systemd:
    name: '{{ item }}'
    state: reloaded
  loop:
    - "{{ samba_smb_service | default('smb') }}"
    - "{{ samba_nmb_service | default('nmb') }}"
  when: samba_config.changed

