- name: restart_samba
  systemd:
    name: '{{ item }}'
    state: restarted
  loop:
    - smb
    - nmb
  when: samba_install.changed

- name: reload_samba
  systemd:
    name: '{{ item }}'
    state: reloaded
  loop:
    - smb
    - nmb
  when: samba_config.changed
